import { useEffect, useState } from 'react';
import { AlertTriangle, Boxes, Search } from 'lucide-react';
import api from '../api/axios';
import Loading from '../components/Loading';
import EmptyState from '../components/EmptyState';

export default function Inventory() {
  const [inventory, setInventory] = useState([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { api.get('/sales-orders/inventory').then((res) => setInventory(res.data.data)).finally(() => setLoading(false)); }, []);
  const filtered = inventory.filter((item) => `${item.product.name} ${item.product.sku}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-brand-600">Warehouse control</p><h1 className="page-title mt-1">Inventory</h1><p className="page-subtitle">Monitor physical, reserved, and available stock in real time.</p></div><div className="relative"><Search size={17} className="absolute left-3 top-3 text-slate-400" /><input className="input-field w-72 pl-9" placeholder="Search products..." value={query} onChange={(e) => setQuery(e.target.value)} /></div></div><div className="grid gap-4 sm:grid-cols-3"><div className="panel p-5"><p className="text-sm text-slate-500">Products tracked</p><p className="mt-2 text-3xl font-bold">{inventory.length}</p></div><div className="panel p-5"><p className="text-sm text-slate-500">Total available</p><p className="mt-2 text-3xl font-bold text-emerald-600">{inventory.reduce((sum, i) => sum + i.availableQuantity, 0)}</p></div><div className="panel p-5"><p className="text-sm text-slate-500">Low stock items</p><p className="mt-2 text-3xl font-bold text-amber-600">{inventory.filter((i) => i.availableQuantity < 10).length}</p></div></div><div className="table-shell">{loading ? <div className="p-5"><Loading /></div> : filtered.length ? <div className="overflow-x-auto"><table className="w-full"><thead><tr><th>Product</th><th>Physical stock</th><th>Reserved</th><th>Available</th><th>Indicator</th></tr></thead><tbody>{filtered.map((item) => { const low = item.availableQuantity < 10; return <tr key={item.id}><td className="font-semibold text-slate-800"><div className="flex items-center gap-3"><div className="rounded-lg bg-slate-100 p-2 text-slate-500"><Boxes size={16} /></div><div>{item.product.name}<p className="text-xs font-normal text-slate-400">{item.product.sku}</p></div></div></td><td>{item.physicalQuantity}</td><td>{item.reservedQuantity}</td><td className={`font-bold ${low ? 'text-amber-600' : 'text-emerald-600'}`}>{item.availableQuantity}</td><td>{low ? <span className="inline-flex items-center gap-1 text-xs font-semibold text-amber-600"><AlertTriangle size={14} /> Low stock</span> : <span className="text-xs font-semibold text-emerald-600">Healthy</span>}</td></tr>; })}</tbody></table></div> : <EmptyState title="No inventory found" />}</div></div>;
}
